# Exercise 18 - Cows and bulls
#Create a program that will play the “cows and bulls” game with the 
# user. The game works like this:

# Randomly generate a 4-digit number. Ask the user to guess a 4-digit 
# number. For every digit that the user guessed correctly in the 
# correct place, they have a “cow”. For every digit the user guessed 
# correctly in the wrong place is a “bull.” Every time the user makes 
# a guess, tell them how many “cows” and “bulls” they have. Once the 
# user guesses the correct number, the game is over. Keep track of 
# the number of guesses the user makes throughout teh game and tell 
# the user at the end.

# Say the number generated by the computer is 1038. An example 
# interaction could look like this:

#   Welcome to the Cows and Bulls Game! 
#   Enter a number: 
#   >>> 1234
#   2 cows, 0 bulls
#   >>> 1256
#   1 cow, 1 bull
#   ...

# Until the user guesses the number.

# import random
# import string

# def cows_and_bulls():
# 	r_broj = random.sample(string.digits, k=4)
# 	user_num = input('Welcome to the Cows and Bulls Game!\nEnter a 4 digit number: ')
	
# 	guesses = 0
# 	cows = 0
# 	bulls = 0

# 	for i in user_num:
# 		if i in r_broj:
# 			return bull + 1
# 		return cow + 1
# 	print(int(cows, bulls))
# cows_and_bulls()

	# while True:
	# 	if user_num is not in range(5):
	# 		print('Enter a 4 digit number: ')
	# 	elif user_num[e] == r_broj[a]:
	# 		print('1 cow, 0 bulls')
	# 	elif user_num[e] == r_broj[a] and user_num:
	# 	elif user_num == r_broj:
	# 		print('Congratulations! You guessed correct!')
	# 	guesses += 1
	# print(f'You took {guesses} guesses!')


# for x in user_num == j in r_broj:
# 			print()

##############################################
# Rješenje sa comments-a
# Ja sam dodao import string i random.sample...

import random
import string

print('Welcome to the Cow Game')

def CowGame():
	bull = 0
	cow = 0
	guesses = 1
	num = random.sample(string.digits, k=4)
	guess = 0
	guess = input('Enter a 4 digit number: \n')
	
	# while True:
	# 	try:
	# 		guess = input('Enter a 4 digit number: \n')		
	# 		if len(guess) == 4 and guess.digits():
	# 			game()
	# 	except:
	# 		print('That wasnt a 4 digit number.')
	

	while num != guess:
		for i,c in enumerate(num):
			if guess[i] == num[i]:
				cow += 1
			else:
				for s, b, in enumerate(guess):
					if num[i] == guess[s]:
						bull += 1
		print('{} cow, {} bull'.format(cow, bull))
		bull = 0
		cow = 0
		guesses += 1
		guess = input('Guess again! \n')

	while num == guess:
		print('You guessed right! Number: {}, Guesses: {}'.format(num, guesses))
CowGame()

input('Press<enter>')
